### ISSUE TITLE
Log errors when verifying vCenter session validity

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1174]
**Describe the solution you'd like**
Expose/log the error while creating/fetching sessions back from vCenter.

**Anything else you would like to add:**
Currently, CAPV swallows the error from vCenter while verifying the validity of existing sessions in the session cache. This problem was masking a Permissions issue in a specific usecase. 
Rather than swallowing the error, logging it would further help debugging such issues.

**Environment:**

- Cluster-api-provider-vsphere version: v0.3.16
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

/kind feature

**Comment by srm09** [comment]
@AartiJivrajani Were you able to make any progress on this one? Lemme know if you need help with this.

**Comment by AartiJivrajani** [comment]
I haven't gotten around to working on this unfortunately! I will take a look at this later this week.

**Comment by srm09** [comment]
@aartij17 If you have not been able to look into this one, maybe we could add this back to the list of `help wanted` issues.
/remove-lifecycle stale

**Comment by AectannArd** [comment]
If this issue is all about [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/release-0.3/pkg/cloud/vsphere/context/session.go#L49) exception swallowing then this piece of code has been heavily refactored ever since in [commit](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/88b5254d3da9fe18c0476ec01a365831594a5e7b#diff-59fbb0bb5dfeeb4f123f1e9e0a3d12c38a60b839e113b29868cb905755639e13) and the problem is not relevant any more. Except the case when someone uses as outdated as `release-0.3`.

@srm09 
is this issue about backporting error check into `release-0.3` branch or is it just stale?

**Comment by sbueringer** [comment]
@zhanggbj When you have some time, can you please check if this issue still makes sense?

**Comment by zhanggbj** [comment]
Currently for cached session, capv will do following checks and report errors if any, so I assume this issue is no longer existed.
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/session/session.go#L131-L142

@srm09 WDYT?

**Comment by sbueringer** [comment]
Thx @zhanggbj for checking. I also checked the entire session.go file. All errors are handled now.

Let's please link to code if we create issues like this in the future, this safes us a lot of time.

/close
