### ISSUE TITLE
vSphere VM spec stores UUID instead of MoRef ID

### ISSUE THREAD

**Issue by saksham189** [kubernetes-sigs/cluster-api-provider-vsphere#1313]
/kind feature

**Describe the solution you'd like**
Looking through the code I see that we store the UUID in the VSphereVMSpec. 
But when we have to perform an operation on the VM we have to first make an API call to get the managed object reference. I am wondering why we cannot store the managed object reference id in the spec so, that we can avoid making this API call everytime we need to perform an operation on the VM.
What is the use case of storing the UUID? 

**Anything else you would like to add:**
No

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by omniproc** [comment]
VMware wanted to get rid of MoRef a long time ago. Instance.UUID (not to be confused with BIOS.UUID) was implemented to be a better, more universal approach.
However AFAIK UUID never has seen much adoption by any tool mainly because UUID is rather unknown and MoRef IDs are shorter and thus easier to use by humans. 

The *correct* way moving forward would be using UUIDs since they, at some point in the future, may replace MoRef and MoRef might get deprecated. However I'm not aware of such plans and I doubt it will ever happen since to many solutions still rely on MoRefs. 

So, why not just safe both and use whatever is more convenient for a given task? 


P.S.:
Both, Instance UUID and MoRef are only considered unique within a single vCenter. So if handling multiple vCenters in addition you'll have to keep a reference to the vCenter e.g. using it's connection FQDN (VMware recommands the vCenter UUID AFAIK since FQDN might point to a different vCenter at some point in time (e.g. migration / upgrades).

**Comment by srm09** [comment]
/close
The current UUID approach seems to be working fine, and following @omniproc's reply seems like it is the correct approach for the sake of posterity.
