### ISSUE TITLE
Webhook certificate didn't renew

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api-provider-vsphere#1333]
/kind bug

**What steps did you take and what happened:**
I installed a new CAPV cluster on an existing 0.4 management cluster. Machines didn't come up properly and reviewing the capv-controller logs I saw this.

```
E1222 16:24:24.889989       1 controller.go:302] controller/vspherevm "msg"="Reconciler error" "error"="Internal error occurred: failed calling webhook \"validation.vspherevm.infrastructure.x-k8s.io\": Post \"https://capv-webhook-service.capv-system.svc:443/validate-infrastructure-cluster-x-k8s-io-v1alpha4-vspherevm?timeout=10s\": x509: certificate has expired or is not yet valid: current time 2021-12-22T16:24:24Z is after 2021-12-13T03:35:12Z" "name"="test-md-0-7c84cffbf6-dsxnh" "namespace"="test" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="VSphereVM"
```

Further investigation shows the webhook exists but the certificate object associated to that service no longer exists.

```
NAMESPACE                           NAME                                      READY   SECRET                                            AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-serving-cert       True    capi-kubeadm-bootstrap-webhook-service-cert       54d
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-serving-cert   True    capi-kubeadm-control-plane-webhook-service-cert   54d
capi-system                         capi-serving-cert                         True    capi-webhook-service-cert                         54d
```

**What did you expect to happen:**
I'd have expected the certificate to have been automatically renewed and for the cluster to come up properly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 0.4.4
- Kubernetes version: (use `kubectl version`): 1.20.2 
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by kbreit** [comment]
@josh-ferrell I should note when I did that `kubectl get certificates` it had the `-A` so that's the only certificates installed in the cluster. There is no `capv-serving-cert` on the cluster anymore.

**Comment by kbreit** [comment]
No logs for `capv` in cert-manager. Could have phased out a while ago though.

**Comment by josh-ferrell** [comment]
@kbreit I'm not sure why the capv-serving-cert Certificate resource is missing but without it I would expect cert-manager not to be able to renew the cert. I'm making a few assumptions that you may want to check.

- The capv-webhook-service-cert secret exists because the capv-controller-manager mounts it and the pod wouldn't start if the secret was gone.
- The capv-webhook-service-cert secret has the annotations cert-manager.io/certificate-name referencing a Certificate resource and cert-manager.io/issuer-name referencing the Issuer the Certificate used. By default this is capv-selfsigned-issuer

If the points above are true, verify the issuer still exist and you can recreate the certificate. You may need to kick the cert-manager pod but it should recognize the cert in the capv-webhook-service-cert secret has expired and renew it. If not you can delete the secret and cert-manager will recreate it then the capv-controller-manager pod will need to be restarted.

If the secret has the annotation cert-manager.io/issuer-name but the issuer doesn't exist then it did at one time. Short of someone accidentally deleting the issuer/certificate for capv the only other time I've seen something similar happen is after upgrading cert-manager when they had deprecated older api versions.

**Comment by kbreit** [comment]
The `capv-webhook-service-cert` secret exists and has the following annotations:

```
(⎈ |supervisor-management:prometheus)~ % kubectl -n capv-system get secret capv-webhook-service-cert -ojson | jq '.metadata.annotations'
{
  "cert-manager.io/alt-names": "capv-webhook-service.capv-system.svc,capv-webhook-service.capv-system.svc.cluster.local",
  "cert-manager.io/certificate-name": "capv-serving-cert",
  "cert-manager.io/common-name": "",
  "cert-manager.io/ip-sans": "",
  "cert-manager.io/issuer-group": "",
  "cert-manager.io/issuer-kind": "Issuer",
  "cert-manager.io/issuer-name": "capv-selfsigned-issuer",
  "cert-manager.io/uri-sans": ""
}
```

However, `capv-selfsigned-issuer` doesn't exist, only `capi-*` issuers.

```
(⎈ |supervisor-management:prometheus)~ % kubectl get issuer -A
NAMESPACE                           NAME                                           READY   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-selfsigned-issuer       True    69d
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-selfsigned-issuer   True    69d
capi-system                         capi-selfsigned-issuer                         True    69d
```
Do I need to recreate the certificate resource as well? I recreated the issuer manually based on an issuer manifest from another CAPV cluster.
