### ISSUE TITLE
Flake in the unit/integration test suite

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1391]
/kind bug

**What steps did you take and what happened:**
We have observed flakes while running the tests using the `pull-cluster-api-provider-vsphere-test` job. Specifically, the test below contributes to most of the flakes in the CI:
```
=== RUN   TestCreate
I0201 01:52:09.076452   25002 clone.go:52] fake-controller-manager/fake-controller/fake-vm/vcenter "msg"="starting clone process"  
I0201 01:52:09.079508   25002 clone.go:78] fake-controller-manager/fake-controller/fake-vm/vcenter "msg"="linked clone requested"  
I0201 01:52:09.079608   25002 clone.go:82] fake-controller-manager/fake-controller/fake-vm/vcenter "msg"="searching for current snapshot"  
I0201 01:52:09.092838   25002 clone.go:249] fake-controller-manager/fake-controller/fake-vm/vcenter "msg"="cloning machine"  "cloneType"="fullClone" "name"="fake-vm" "namespace"="default"
    create_test.go:67: failed to clone vm
--- FAIL: TestCreate (0.26s)
FAIL
FAIL	sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi	0.419s
```

**What did you expect to happen:**
We would expect the tests to pass consistently without any flakes

**Anything else you would like to add:**
n/a

**Environment:**

- Cluster-api-provider-vsphere version: `latest`
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by ditsuke** [comment]
I'm investigating this flake at the moment. I think it's highly likely due to the asynchronous nature of tasks including cloning virtual machine on the simulator, which could mean that we're checking for successful creation of the VM while its still in progress. As a hack-in-testing, I blocked the main goroutine with a time.Sleep which seems to consistently eliminate this flake.

As a potentially related issue and reference on the upstream govmomi repository: https://github.com/vmware/govmomi/issues/2393
