### ISSUE TITLE
Provision to upgrade hardware version during VM clone operations

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#1652]
Talking w @yastij , there sounds like there are ways 
to upgrade HW versions ( i.e. 15 -> 17 , to support GPU scheduling)  dynamically, w/o needing an OVA
that is bound  to an ESXi.

**Comment by jayunit100** [comment]
Looking around on the internet, https://github.com/rancher/rancher/issues/25174 seems to be similar to something akin to .... ?

```
govc vm.power -off <vm_name>
govc vm.upgrade -vm  <vm_name>
govc vm.power -on <vm_name>
```

**Comment by geetikabatra** [comment]
@srm09 ^^
The idea is to add a field in `VirtualMachineCloneSpec` something like `vmxVersion`, and then in the `vmReconciler` before powering the machine on, vmxVersion is set.

**Comment by srm09** [comment]
/retitle Provision to upgrade hardware version during VM clone operations

**Comment by srm09** [comment]
Adding my thoughts here,
Setting the hardware version is not allowed to be set during clone operations, it is either obliged only in create or upgrade VM tasks. Relevant docs [here](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.ConfigSpec.html), look for the definition of the `version` parameter in here.

Since we are planning to accept the vmx-version from the user
1. wait for the VM to be cloned 
2. once the clone operation for the VM has been initiated, [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/067f2a678c8f3e18baa8db5e5374c7a3e82d1b2e/pkg/services/govmomi/service.go#L74) should return a VM object 
3. add a new method `reconcileHardwareVersion()` after the `reconcileUUID()` method
4. the new method, checks the current hardware version of the VM and if different than the one specified in the spec, queues a [UpgradeVM_Task](https://vdc-download.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.VirtualMachine.html#upgradeVirtualHardware) with the version specified by the user.
5. On subsequent reconciles, once the hardware version returned is the same, control will move on to the next method.

**Comment by srm09** [comment]
There is no straight forward method exposed by `govmomi` to expose the hardware version of the object, you might have to get creative with the property collector exposed by the `VirtualMachine` object and get the value of the property. Couple of places where I found the property was `config.version` and `guest.version` on the `VirtualMachine` object. 

I am not sure if the first one is available for us, since the docs say that this is set when the virtual machine is created. Not 100% sure if it is talking about the create VM operation, or just talking about VM creation in the general sense. Hence, try the second path and treat the first as a backup.

To get the govmomi object types to use, run a ` govc vm.indo -dump <vm-name>` command against an existing VM.
