### ISSUE TITLE
CAPV looking for KubeadmControlPlane despite using non-kubeadm control plane provider #2

### ISSUE THREAD

**Issue by bnason** [kubernetes-sigs/cluster-api-provider-vsphere#1863]
/kind bug

**What steps did you take and what happened:**
Deploying CAPV to a fresh local bootstrap cluster (talos v1.3.6) with the Talos Control Plane Provider and the Talos Bootstrap Provider.
The `capv-controller-manager` pod fails health checks and is repeatedly restarted with the following message:
`source.go:139] "controller-runtime/source: if kind is a CRD, it should be installed before calling Start" err="no matches for kind \"KubeadmControlPlane\" in version \"controlplane.cluster.x-k8s.io/v1beta1\"" kind="KubeadmControlPlane.controlplane.cluster.x-k8s.io"`

**What did you expect to happen:**
No error message and manager works as expected

**Anything else you would like to add:**

Follow up to Issue #1702

I compiled my own copy of the manager container commenting out the following lines which resulting in a working cluster.

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/clustermodule_reconciler.go#L186-L199

@srm09 also pointed out in slack this: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/6df9540a3566d3ea64f72759664bf9db163c961f/controllers/vspherecluster_controller.go#L166

**Environment:**

- Cluster-api-provider-vsphere version: v1.6.0
- Kubernetes version: (use `kubectl version`): v1.26.2
- OS (e.g. from `/etc/os-release`): Talos v1.3.6

**Comment by srm09** [comment]
This happens because the support for node anti affinity includes an implicit dependency on KCP being the control plane provider. Due to this, all parts of the node anti affinity functionality need to be feature flagged.
The TODO above shows that the controller for `VSphereCluster` adds the watches it needs for node anti-afifnity outside of the feature flag. This is why, the logs were showing the above error message.

Fixing this would require moving the watch logic under the same feature flag.
