### ISSUE TITLE
Rework KCP remediation e2e test

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1871]
/kind bug

**What steps did you take and what happened:**
After upgrade to CAPI 1.4, the semantics of KCP remediation test have been updated which requires a special communication setup between management cluster and workload cluster under creation. This test would need to be reworked specifically in CAPV to create a highly available cluster and then mark a node unhealthy for MHC to remediate it.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
This is a test which specifically tests core KCP functionality. In my opinion we don't have to run it in CAPV.

@fabriziopandini WDYT?

**Comment by fabriziopandini** [comment]
I think that it is not worth the effort
KCP remediation behavior is not relevant from a provider PoV (it is like any other machine deletion operation)

Also, the test implementation requires connectivity from machines to the management cluster in order to control when machines bootstrap, if bootstrap should fail and pass etc. All those things are not required in any production cluster, and setting up this in CI could be challenging, and potentially have some security concern.
