### ISSUE TITLE
handle the case when vm clone task do not finish timely

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/cluster-api-provider-vsphere#200]
cluster-api vSphere relying on vm-clone to create VM, the vm-clone task takes some time, potentially this task can take unreasonable long time (or forever), the current design is to let reconcile loop wait the task until finish.

the impact to customer is: when this happen, customer will not able to see success (a node) or a failure .

the question is: should clusterapi enforce a deadline for this task, so that controller has chance to
start a new clone task if the previous one got stuck. (although the new clone task is not guarantee to success if there is problem with vSphere infrastructure), the point is to give controller the chance to overcome some ephemeral issues at infra.

cc @sidharthsurana @sflxn @dougm

**Comment by sflxn** [comment]
@figo I think we should add this to the next public meeting's agenda for discussion.  You are right that the controller takes an optimistic approach to creating the VMs.  We need to build in a little more fault tolerance.  We may want to create a whole epic around fault tolerance for creation/deletion.  I'm sure there are other areas where we're taking an optimistic approach.

**Comment by moshloop** [comment]
I think waiting in the main control loop is generally not recommended, from what I have heard it is better to requeue and check the status on the next reconcile run.

This would have the added advantage of being able to spin up multiple instances in parallel greatly reducing cluster creation time.

**Comment by akutz** [comment]
Hi @moshloop,

I don't know you, but as I triage your responses, I think I like you :)

> This would have the added advantage of being able to spin up multiple instances in parallel greatly reducing cluster creation time.

Yep. I do this already in another project with a cap on the number of parallel operations.

However, for failed deployments, there's simply no great to handle this. Whether or not we wait on the main control loop (we will likely use a goroutine, so it's a non issue), the problem is we can't actually know if something failed -- only that it's not online *yet*.

At best we will likely support:

1. Deploy machine
2. Up yet? Repeat until dry.
3. After X time or Y cycles if VM still wet then throw it out and start over

**Comment by moshloop** [comment]
I think we should follow the pod model of readiness/conditions and back off loops.

i.e. In every loop check the readiness of the vm (as reported by vm-tools), report state changes from:

- MachineCreating
- MachineCreated
- MachingBooting
- MachineBooted (Reported by vm-tools)
- MachineIpReported (Reported by vm-tools)
- MachineReachable (As visible by the controller)
- MachineReady (As reported by the api-server)

For the proactive checks (Reachable, ready) start often and then backoff.
For all others, check often and report, but don't block the creation of other machines, so if 1 machine out of 10 fails, you still have 9 running.

I think the retry-mechanism should also be external to the main loop. If a machine fails or takes very long to start I think it would be very environment specific on what todo e.g. (retry or not, back off or not, leave the vm for forensics or not). 

i.e. Each end-user could then deploy a controller (or create a custom controller) that looks for machines in failed or unacceptably long startup times and terminate them etc..)

**Comment by akutz** [comment]
Hi @moshloop,

This is great stuff. I wonder if this conversation isn't one that should occur at at the CAPI community since the readiness process and resolution model for failed deployments is applicable to all CAPI providers. @timothysc, do you happen to know if there an existing issue for discussing this?

**Comment by detiber** [comment]
The biggest challenge upstream in cluster-api is the [lack of remote node references](https://github.com/kubernetes-sigs/cluster-api/issues/520), which is what we would usually attempt to use to check for machine/node readiness. Once that is resolved, then we could easily add some type of a generic timeout condition as well. Until then, I'm afraid that any type of timeout would need to be handled on the provider level.

**Comment by timothysc** [comment]
We're planning to try and address this in v1alpha2.
