### ISSUE TITLE
Improve unit test result visualiziation in testgrid

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2122]
In core CAPI I changed the way we run unit tests a while back so we can see the details of the unit test report in testgrid & in the Prow UI, e.g.:
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-test-main
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-test-main/1685949765738565632

This makes it easy to see which tests failed in the Prow UI and it also makes it possible to see which tests are flaky via testgrid and k8s-triage.

Notes:
* I think we should do this for test and test-integration (but please double check if I'm missing something)
* Let's make sure this doesn't break [test-coverage](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-test-coverage)

**Comment by sbueringer** [comment]
cc @chrischdi 

When you have some time would be nice if you can take this over. You can compare with core CAPI, but it might be as simple as running `make test-cover` instead of `make test` (+ we would need a similar target for test-integration)

**Comment by chrischdi** [comment]
What we need for this is junit*.xml files in artifacts instead of coverage.

Example for `test-integration`: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/2140/pull-cluster-api-provider-vsphere-test-integration-main/1686704256050008064

Following plan:

Adjust makefile to:
* provide a junit result file at `test-integration` (directly possible because we run the tests using ginkgo, similar to the e2e tests)
* add a `test-junit` target (similar to the core CAPI one) and use `test-junit` at prowjobs instead of `test`

**Comment by sbueringer** [comment]
Sounds good!

**Comment by sbueringer** [comment]
@chrischdi Maybe you can take a quick look tomorrow to check all jobs still work / give us the results

/reopen

**Comment by chrischdi** [comment]
Looks good for all periodics now!

/close
