### ISSUE TITLE
ESXi: Support thin cloning

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-provider-vsphere#289]
The current implementation causes thick clones, which eats into my laptop disk unnecessarily. 

Please assign to me, I have a working implementation.

**Comment by akutz** [comment]
Hi @moshloop,

I look forward to seeing it! Let's set up a call to discuss this as we may need to rework your implementation as the method of deploying VMs is changing. We're going to move to the following model:

**Cluster Resolve**
1. Import OVA into content library

**Machine Create**
1. Deploy VM from OVA in content library

However, because thin-clones is definitely a must-have for some users, I think we should definitely support an enhanced version of the above model:

**Cluster Resolve**
1. Import OVA into content library
2. Deploy OVA as template

**Machine Create**
1. Thin-clone template created in "Cluster Resolve" step as new machine

Thoughts?

**Comment by moshloop** [comment]
I think OVA's should be a helper, not a dependency in cluster or machine creation. (i.e. `--create-template-from-ova` option to clusterctl. 

Many organizations will want to use an image created and maintained internally that bundles in their combination of security, management, monitoring tools etc. Forcing the use of an ova, prevents this and/or makes it much harder to fit into common image pipelines. 

In a multi-cluster world, especially where integrations tests spin up an entire cluster for a PR, importing an OVA and then cloning it would also be unnecessarily long.

**Comment by akutz** [comment]
Hi @moshloop,

Thank you for the continued and fantastic feedback!

> I think OVA's should be a helper, not a dependency in cluster or machine creation. (i.e. --create-template-from-ova option to clusterctl.

We still plan to support deploying from an existing OVA in the content library or from a template for linked clones. However, the default mode will be to automatically import an OVA. And it won't be *that* time consuming as it will happen once in the Cluster provision (not per machine), and only if the OVA doesn't already exist in the content library.

> Many organizations will want to use an image created and maintained internally

The process for creating images is [documented](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/build/images), and a custom can absolutely create their own images as long as the process is followed in order to ensure that the custom images meet the requirements. One reason for this model is to support the security and air-gap scenarios to which you refer. For example, if you've got the `centos-7-kube-v1.13.6.ova` you can use it to deploy Kubernetes at any release since `kubeadm` can pull images for different Kubernetes versions. However, if you're air-gapped, the OVA includes everything you need to deploy Kubernetes baked into the image.

Thank you again!

**Comment by moshloop** [comment]
If the plan is to support either OVA or a template for thin/linked cloning then I don't see any issues as an end-user.

As a developer/maintainer, I would want as few critical path's to provisioning as possible. The more path's available, the larger the test matrix becomes and the higher the likelihood of falling through the cracks become. 

If OVA support is added as a helper to create the templates should they not exist, then it does not form part of the critical path. The mental model for thinking about how a cluster is created and could fail does not grow to how the OVA's are found, imported and transformed into templates.

Just my 2c

**Comment by akutz** [comment]
Hi @moshloop,

So let me get the refactored bits for the new deployment model in place, and then I can assign you this issue so you can enhance it with thin provisioning. Does that work?

**Comment by moshloop** [comment]
👍

**Comment by moshloop** [comment]
Issue #400 now covers this
/close
