### ISSUE TITLE
[docs] add network requirements in readme.md

### ISSUE THREAD

**Issue by shawnho1018** [kubernetes-sigs/cluster-api-provider-vsphere#410]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Hope our document should explicitly specify 
1. the config client must connect to control-plane VM or the installation would fail. 
2. addon.yaml should apply to the workload cluster not management cluster

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 0.3.0
- Kubernetes version: (use `kubectl version`): 1.13.6 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by akutz** [comment]
Doesn’t the doc note requirement one? Also, the second note is incorrect. The addons is primarily for the management cluster bootstrapped with clusterctl, not the workload clusters (although it could be used for that as well if you want).

**Comment by shawnho1018** [comment]
Hi, I hope to clarify my earlier statement. Don't want to get you confused. 
The addon I meant is the addon.yaml in workload folder, not the one for management cluster folder. This addon.yaml is mainly for Calico deployment for now. It should be applied to workload cluster. If it does not apply,  workload cluster would be in Not-Ready state. I have to manually apply addon.yaml kubectl --kubeconfig ./workload-kubeconfig apply -f ./addons.yaml) to make it work.

**Comment by akutz** [comment]
Hi @shawnho1018,

> I have to manually apply addon.yaml kubectl --kubeconfig ./workload-kubeconfig apply -f ./addons.yaml) to make it work.

That is correct. I too was confused by this when I started working on Cluster API a month ago. I initially operated under the assumption that the goal of a CAPI provider is to deploy clusters on which workloads may be scheduled. It turns out that was a false assumption.

It was the agreement of the Cluster API community that applying CNI to anything other than the initial management cluster would be considered too prescriptive. So instead, the `addons.yaml` is only applied automatically by `clusterctl to the initial management cluster, and it's totally up to the user to decide what CNI to apply to any guest/workload clusters deployed later.

I agree this seems awkward, but it was explained to me that CAPI is a tool on which other tooling should be built, and that CAPI providers are designed to stand up an API server that is then available to be customized/provisioned however a user/additional tooling wishes.

**Comment by shawnho1018** [comment]
Thanks for your explanation. It's clear to me now. 
I simply hope to add this "hint" in the readme.md since addon.yaml is the only yaml applied to a different target. All others, including machine, machineset, cluster.yaml, were all applied to management cluster, which have been clearly documented.
