### ISSUE TITLE
Multi-tenant manager support

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#528]
/kind feature

**Describe the solution you'd like**
In v1a1, vSphere credentials were bound to the CAPV `ProviderSpec` in the CAPI `Cluster` resource. This design created a feature as a side-effect -- the ability to support multi-tenant management domains since the credentials used to deploy vSphere resources were tied to the CAPI `Cluster` resource, not the CAPV manager itself.

In v1a2 the credentials used to deploy vSphere resources are no longer part of any Kubernetes resource, but instead tied to the CAPV manager. This model is more secure, but it limits the credentials that may be used to deploy vSphere resources to a single credential set.

This issue tracks the conversation around support for of a proper, multi-tenant approach to supporting multiple vSphere credential packages. 

Solutions proposed thus far are:

1. One CAPV management cluster per tenant
    * If multi-tenancy is desired, then a separate management cluster should be used to isolate credentials used to interact with vSphere
2. Kubernetes secrets that store vSphere credential information and may be selected:
    a. Explicitly by a `VSphereCluster` resource via new fields `Secret` and `SecretNamespace`
    b. Implicitly by a `VSphereCluster` resource via the CAPV manager selecting the credentials based the target vSphere endpoint specified in the `VSphereCluster` resource

I lean toward solutions `1` or `2b`. I don't think it should be up to a `VSphereCluster` spec to explicitly select the name of the secret to use for deploying vSphere resources. This implies that the person creating a cluster must simply know the name of the secret to use it.

Additionally, I favor `1` more than `2b` because the former also allows the restriction of the Kubernetes service account used by the CAPV manager to access secrets.

cc @dvonthenen 

Related to https://github.com/kubernetes/cloud-provider-vsphere/pull/241

**Comment by vukg** [comment]
Use case for that feature that we are working on is multi-site multi-infrastructure on-prem Kubernetes engine that provisions worker clusters in different administrative domains our technology stack at networking unit of Deutsche Telekom. 

Due to network segmentation design we are running multiple vCenter instances which can not be realistically unified due to segregation of concerns (management domain vs. multiple service domains). 

We would like to avoid having to cascade control clusters with CAPV in them just to get possibility to target multiple vCenters.

![image](https://user-images.githubusercontent.com/52979324/70228807-51c8e200-1755-11ea-838f-0c4adf4d820a.png)

**Comment by akutz** [comment]
ping @pdaigle
