### ISSUE TITLE
Error writing Crisocket information for the control-plane node

### ISSUE THREAD

**Issue by ac06012014** [kubernetes-sigs/cluster-api-provider-vsphere#720]
/kind bug

Hi team,

I've encountered some troubles with this OVA ubuntu-1804-kube-v1.16.3.ova during cloud-init process on the management cluster as you can see in /var/log/cloud-init-output.log:
```
[kubelet] Creating a ConfigMap "kubelet-config-1.16" in namespace kube-system with the configuration for the kubelets in the cluster
error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
```

No problem with PhotonOS.

I'm not sure if this is a bug.

**Environment:**
- Kind v0.6.1 + go1.13.4 + clusterctl (v0.2.9) to bootstrap the cluster
- Cluster-api-provider-vsphere version: 0.5.4
- Kubernetes version: (use `kubectl version`): 1.16.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by akutz** [comment]
Hi @ac06012014,

Thank you for filing this. Per our debug session on k/k Slack, we determined this to be an issue with https://github.com/kubernetes-sigs/image-builder/pull/113, corrected by https://github.com/kubernetes-sigs/image-builder/pull/114. Unfortunately it seems machine images were built after https://github.com/kubernetes-sigs/image-builder/pull/113 merged, but not after https://github.com/kubernetes-sigs/image-builder/pull/114 merged.

I'm going to ping @codenrhoden to make him aware of the situation as he's who builds the images. Currently images are only built and published manually, and I forgot to ask Travis to publish new images after https://github.com/kubernetes-sigs/image-builder/pull/114 merged, so that's on me.

Thanks!

**Comment by akutz** [comment]
ping @randomvariable Just wanted you to be aware of this potential bug as a result of the incorrect boot stage order (that you fixed).

**Comment by yastij** [comment]
ping @ac06012014 - any news on this ? can you use a new image ?

**Comment by ac06012014** [comment]
Hi Yassine,
It works with photon OS. I didn't find time to test again with ubuntu.

**Comment by yastij** [comment]
@ac06012014 - closing this as this is working, feel free to re-open if you're still seeing an issue
