### ISSUE TITLE
The task is pending when there is no resource pool in vCenter

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api-provider-vsphere#876]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If not setting resource pool in vCenter, fail to create Kubernetes cluster

**What did you expect to happen:**
Expect there is no dependency of resource pool when creating cluster

**Anything else you would like to add:**
We also tried use the root resource pool, enter */Resource, but it also failed.

kubectl logs capv-controller-manager-b46fffc8c-pclmg -n capv-system -c manager
The log as below:
E0329 13:17:25.639473       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile VM: unable to get resource pool for \"infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereVM default/test-no-resource-controlplane-0\": **

> resource pool '*/Resource' not found"

**  "controller"="vspherevm" "request"={"Namespace":"default","Name":"test-no-resource-controlplane-0"}

**Environment:**
CAPV: v0.6.0

**Comment by yastij** [comment]
the default root resource pool is `*/Resources` 2 cases:
- set `*/Resources` at `vsphereCluster` level and no need to override at the `vsphereMachine` level
-  if you are setting a different resourcePool on the `vsphereCluster`, make sure to explicitly override in the vsphereMachine spec with the root resource pool

**Comment by monfardineL** [comment]
I have the same scenario but I think the problem resides on another side.
I have a licensed vCenter Server 6 **Standard**, which doesn't support **DRS** and consequently doesn't support also the creation of resource pools, and even through VMware documentation says there's a default resource pool, I don't think it's capable of distribute the VMs among the hosts on cluster, as it's supposed to happen.

I've already had quite some problems with automation tasks because of that, but it's kinda expensive to get an enterprise license with DRS support.

My suggestion is to allow pointing to a specific vCenter host on config file, and ignore the resource pool option. Maybe let it clear that this way the balancing of resources is of responsibility of the user (as I am already used to).

**Comment by ncdc** [comment]
@luniHw were you able to test using `*/Resources` (note, there is an **s** at the end of the word)?

@monfardineL would you mind filing a separate issue if you're looking for CAPV to work on vSphere Standard?

**Comment by monfardineL** [comment]
> @monfardineL would you mind filing a separate issue if you're looking for CAPV to work on vSphere Standard?

I commented here because I think it's related, but I've already created issue #941.

**Comment by yastij** [comment]
closing this, please re-open the issue, if it doesn't work for you
