### ISSUE TITLE
Reevaluate bidirectional communication between management and workload clusters

### ISSUE THREAD

**Issue by chipzoller** [kubernetes-sigs/cluster-api-provider-vsphere#882]
/kind feature

**Describe the solution you'd like**
Currently, an assumption within the CAPI project has been made predicated primarily on public cloud networking concepts that communication between management and workload clusters should be unidirectional. That is, the management cluster can speak to the workload cluster but returning any results or info from the workload cluster back to the management cluster is not possible. In situations in public cloud providers such as AWS where VPC communication may not allow this, this is a necessity. However, for vSphere, this is less likely to be the case.

The ability to have bidirectional communication between these clusters would significantly aid the troubleshooting and introspection process. For example, when bringing up the HA Proxy load balancer with NTP inconsistently applied across underlying ESXi hosts results in initial certificate generation failures, this information could be surfaced back to the management cluster and subsequently the operator in order to determine the cause of the cluster build failure.

vSphere contains a few technologies that could be leveraged to deliver this outcome, including the VMware tools, VMCI, or serial port redirection.

**Comment by detiber** [comment]
If the requirement for bi-directional communication can be limited to the scope of just the vsphere infrastructure provider this *might* be okay.

One thing to keep in mind through this is the bootstrapping process of standing up Cluster API, though. In which case the bootstrapping cluster *may* be a `kind` cluster that is running on a local workstation. Can we say that this `kind` cluster will be accessible from the remote infrastructure being provisioned? I don't think we can, since we are not exposing the port from the host running the `kind` cluster and there is no requirement that the bootstrapping cluster be accessible.

**Comment by chipzoller** [comment]
Agree that's not an assumption which can be made, but I think we can make some concessions here. For example, although the bootstrapping cluster _may_ be a `kind` cluster, it could very well be a persistent, dedicated, management cluster also running in vSphere. In such a case, the management cluster, unlike `kind` would not be ephemeral and would (almost certainly) have connectivity out to the deployed clusters.

**Comment by randomvariable** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/issues/2554
