### ISSUE TITLE
vCloud Support for Cluster api

### ISSUE THREAD

**Issue by sachinphogat** [kubernetes-sigs/cluster-api-provider-vsphere#902]
/kind feature

Does cluster-api is planning to support vCloud Director  as we are moving all our vsphere infra to vCloud Director for managing VMs and and if yes, any ETA?

Or is there any way in which we can use current cluster-api-provider-vsphere for managing lifecycle on vCloud Director?

**Comment by vincepri** [comment]
Transferred to CAPV repository

**Comment by yastij** [comment]
thanks @vincepri for moving this. @sachinphogat CAPV's scope is only vsphere, I'd see this as a totally different provider as the API are different

**Comment by kannanvr** [comment]
Hi,
  When it will be available ?

**Comment by randomvariable** [comment]
As discussed previously, vCloud Director's API is different enough to vSphere that it should be treated as a different project which would need to be proposed to SIG Cluster Lifecycle or the VMware User Group.

/close

**Comment by jonkerj** [comment]
I know this issue is closed, and I think that's fair. I was wondering if the question was followed up somewhere in the right place, and if anyone could point me to that. Since both CAPI and VCD are not so obscure anymore, I have a hard time believing that my failed searches for a vcd infrastructure prove it is not there..

**Comment by goelaashima** [comment]
@jonkerj @sachinphogat Checkout https://github.com/vmware/cluster-api-provider-cloud-director which is WIP. Feel free to directly connect with us via github issues on that project itself. 

Thanks
Aashima
